name: Check Pull Request

on:
  pull_request:
    branches: 
     - main

jobs:
  verify:
    defaults:
        run:
          working-directory: .
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 
         - 18.x
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install packages
        run: npm install


      - name: Run lint
        run: npm run lint

      - name: Run test
        run: npm run test